# Generated by Django 5.0.7 on 2024-07-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
